version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: exomonexo

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=exomonexo
      - REDIS_PORT=6379
      - REDIS_DATABASES=16


  bot:
    build: .